const request = require('supertest')
const app = require('../src/01-basic-completion/app')

describe('Basic Completion Functions', () => {
  // 这个文件用于演示测试生成功能
  // 选中函数或类，然后使用 /tests 命令生成测试
  
  test('should be generated by Copilot', () => {
    // 使用 Copilot 生成实际的测试
    expect(true).toBe(true)
  })
})
